/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "client-server.pb-c.h"
void   login__init
                     (LOGIN         *message)
{
  static LOGIN init_value = LOGIN__INIT;
  *message = init_value;
}
size_t login__get_packed_size
                     (const LOGIN *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &login__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login__pack
                     (const LOGIN *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &login__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login__pack_to_buffer
                     (const LOGIN *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &login__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LOGIN *
       login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LOGIN *)
     protobuf_c_message_unpack (&login__descriptor,
                                allocator, len, data);
}
void   login__free_unpacked
                     (LOGIN *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &login__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue login__validation__enum_values_by_number[3] =
{
  { "OK", "LOGIN__VALIDATION__OK", 0 },
  { "IN_USE", "LOGIN__VALIDATION__IN_USE", 1 },
  { "INVALID", "LOGIN__VALIDATION__INVALID", 2 },
};
static const ProtobufCIntRange login__validation__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex login__validation__enum_values_by_name[3] =
{
  { "INVALID", 2 },
  { "IN_USE", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor login__validation__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "LOGIN.VALIDATION",
  "VALIDATION",
  "LOGIN__VALIDATION",
  "",
  3,
  login__validation__enum_values_by_number,
  3,
  login__validation__enum_values_by_name,
  1,
  login__validation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor login__field_descriptors[2] =
{
  {
    "username",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LOGIN, username),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "validation",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(LOGIN, has_validation),
    PROTOBUF_C_OFFSETOF(LOGIN, validation),
    &login__validation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login__field_indices_by_name[] = {
  0,   /* field[0] = username */
  1,   /* field[1] = validation */
};
static const ProtobufCIntRange login__number_ranges[1 + 1] =
{
  { 10, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LOGIN",
  "LOGIN",
  "LOGIN",
  "",
  sizeof(LOGIN),
  2,
  login__field_descriptors,
  login__field_indices_by_name,
  1,  login__number_ranges,
  (ProtobufCMessageInit) login__init,
  NULL,NULL,NULL    /* reserved[123] */
};
