/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_client_2dserver_2eproto__INCLUDED
#define PROTOBUF_C_client_2dserver_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _LOGIN LOGIN;


/* --- enums --- */

typedef enum _LOGIN__VALIDATION {
  LOGIN__VALIDATION__OK = 0,
  LOGIN__VALIDATION__IN_USE = 1,
  LOGIN__VALIDATION__INVALID = 2
} LOGIN__VALIDATION;

/* --- messages --- */

struct  _LOGIN
{
  ProtobufCMessage base;
  char *username;
  protobuf_c_boolean has_validation;
  LOGIN__VALIDATION validation;
};
#define LOGIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&login__descriptor) \
    , NULL, 0,0 }


/* LOGIN methods */
void   login__init
                     (LOGIN         *message);
size_t login__get_packed_size
                     (const LOGIN   *message);
size_t login__pack
                     (const LOGIN   *message,
                      uint8_t             *out);
size_t login__pack_to_buffer
                     (const LOGIN   *message,
                      ProtobufCBuffer     *buffer);
LOGIN *
       login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   login__free_unpacked
                     (LOGIN *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LOGIN_Closure)
                 (const LOGIN *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor login__descriptor;
extern const ProtobufCEnumDescriptor    login__validation__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_client_2dserver_2eproto__INCLUDED */
